#pragma once

// Auto-generated by calibrate.py — do not edit by hand.
// Re-run ./run_calibration.sh to regenerate.
//
// Decoupling matrix: maps 9 baseline-subtracted sensor deltas -> 6 DOF outputs.
// Rows: TX, TY, TZ, RX, RY, RZ  |  Cols: mag1x,y,z  mag2x,y,z  mag3x,y,z

namespace Config {

const float DECOUPLING_M[6][9] = {
    {   16.145511f,   13.908063f,   -6.511877f,    8.511831f,   -2.457025f,   -8.098999f,  -22.065245f,  -15.073424f,    7.719446f },  // TX
    {    0.720876f,   -5.362054f,    6.160021f,   -5.834759f,    6.142860f,    6.071601f,    4.496475f,  -15.545674f,  -14.507836f },  // TY
    {    0.736394f,   -1.653539f,    1.182954f,    0.518428f,    1.106067f,   -0.255691f,   -1.009996f,    0.245162f,   -0.558414f },  // TZ
    {   -0.156866f,   -0.456776f,    0.089768f,    0.064853f,    0.085114f,    0.009614f,   -0.018700f,    0.305999f,    0.113140f },  // RX
    {   -0.569443f,    0.718931f,   -0.565567f,   -0.069216f,   -0.621104f,   -0.120334f,    0.665845f,    0.283971f,    0.473112f },  // RY
    {   -2.137401f,   -0.531771f,    0.824094f,   -1.839706f,   -2.506505f,    0.864780f,    2.603395f,    5.173002f,   -1.226766f }   // RZ
};

}  // namespace Config
